__author__ = 'San Lee'

from colour import WHITE

BACKGROUND_COLOUR = WHITE

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600

TILE_WIDTH = 100
TILE_HEIGHT = 100

MAX_NUM_PLAYERS = 4

TILE_GOLD = 1
TILE_MONSTER = 2
TILE_SHOP = 3
TILE_RESPAWN = 4
TILE_HEAL = 5
TILE_OTHER_EVENT = 6

MONSTER_TYPE_MINION = 1
MONSTER_TYPE_BOSS = 2
MONSTER_TYPE_DEMON = 3

MONSTER_IMG_FILE_PATH = 'img_monsters'
ITEM_IMG_FILE_PATH = 'img_items'

ACTION_RESULT_INVALID = 0
ACTION_RESULT_GOLD_GET = 1
ACTION_RESULT_WIN = 2
ACTION_RESULT_DIE = 3
ACTION_RESULT_SHOP_BUY = 4
ACTION_RESULT_SHOP_SELL = 5
ACTION_RESULT_SHOP_LEAVE = 6
ACTION_RESULT_RESPAWN = 7
ACTION_RESULT_HEAL = 8